version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "area/dependency"
      - "ok-to-test"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "area/dependency"
      - "ok-to-test"
    open-pull-requests-limit: 10
